[versions]
android_gradle_plugin = "8.10.0"
java = "21"
kotlin = "2.2.21"
ksp = "2.2.21-2.0.5"
androidx_room = "2.8.4"

[libraries]
androidx_room_compiler = { module = "androidx.room:room-compiler", version.ref = "androidx_room" }

[plugins]
android-library = { id = "com.android.library", version.ref = "android_gradle_plugin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
